### ISSUE TITLE
Warning: undefined constant ENCODE_AMPERSANDS

### ISSUE THREAD

**Issue by zonky2** [BugBuster1701/contao-easyupdate3#83]
PHP 7.2

```
Warning: Use of undefined constant ENCODE_AMPERSANDS - assumed 'ENCODE_AMPERSANDS' (this will throw an Error in a future version of PHP) in composer/vendor/bugbuster/easyupdate3/easyupdate3.php on line 35

#0 composer/vendor/bugbuster/easyupdate3/easyupdate3.php(35): __error(2, 'Use of undefine...', 'composer/...', 35, Array)
#1 system/modules/core/classes/BackendModule.php(98): easyupdate3->compile()
#2 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#3 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('easyupdate3')
#4 contao/main.php(20): Contao\BackendMain->run()
#5 {main}
```

Gruss

**Comment by BugBuster1701** [comment]
Installiere die aktuelle Version von easyupdate3, da ist der Fehler bereits behoben.

**Comment by zonky2** [comment]
gefunden - der steht als "dev-master" drin und nicht als 3.5.2...
